# -*- coding: utf-8 -*-
"""Copy of Fase2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aK9V8jlQ_bHhgiTnLaL495cVE0hy4XHa

Crie um algoritmo em Python que peça 2 números e imprima o maior deles.
"""

# INSIRA SEU CÓDIGO AQUI

num1 = int(input("Digite um numero: "))
num2 = int(input("Digite um numero: "))

if num1 > num2:
    maior = num1
if num2 > num1:
    maior = num2

print(f"O número maior é : {maior}")

"""Crie um algoritmo em Python que peça um valor e mostre na tela se o valor é positivo ou negativo."""

# INSIRA SEU CÓDIGO AQUI

numero = int(input("Digite um número: "))

if numero > 0:
    print(f"Esse número {numero} é Positivo!")

else:
    print(f'Esse número {numero} é Negativo!')

"""Crie um algoritmo em Python que verifique se uma letra digitada é vogal ou consoante."""

# INSIRA SEU CÓDIGO AQUI
l = str(input('Digite uma letra: ').lower())

if l == 'a' or l == 'e' or l == 'i' or l == 'o' or l == 'u':
    print(f'A letra {l} é vogal')
else:
    print(f'A letra {l} é consoante')

"""Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:
* "Aprovado", se a média alcançada for maior ou igual a sete;
* "Reprovado", se a média for menor do que sete;
* "Aprovado com Distinção", se a média for igual a 10.
"""

# INSIRA SEU CÓDIGO AQUI
nota1 = float(input("Digite uma nota: "))
nota2 = float(input("Digite uma segunda nota: "))

media = (nota1 + nota2) / 2

if media >= 7:
    print("Aprovado Resultado")

if media >= 10:
    print("Aprovado com Distinção")

if media <= 7:
    print("Reprovado")

"""Crie um algoritmo em Python que leia três números e mostre o maior deles."""

# INSIRA SEU CÓDIGO AQUI
num1 = int(input("Digite um numero: "))
num2 = int(input("Digite um numero: "))
num3 = int(input("Digite um numero: "))

if num1 > num2 > num3:
    maior = num1
if num2 > num1 > num3:
    maior = num2
if num3 > num1 > num2:
    maior = num3

print(f"O número maior é : {maior}")

"""Crie um algoritmo em Python que leia três números e mostre o maior e o menor deles."""

# INSIRA SEU CÓDIGO AQUI
num1 = int(input("Digite um numero: "))
num2 = int(input("Digite um numero: "))
num3 = int(input("Digite um numero: "))

if num1 > num2 > num3:
    maior = num1
if num2 > num1 > num3:
    maior = num2
if num3 > num1 > num2:
    maior = num3

if num1 < num2 < num3:
    menor = num1
if num2 < num1 < num3:
    menor = num2
if num3 < num1 < num2:
    menor = num3
print(f"O número maior é : {maior} e o número menor é {menor}")

"""63
96
Faça um programa que pergunte o preço de 5 produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.
"""

# INSIRA SEU CÓDIGO AQUI

p1 = input("Digite o preço 1º produto: ")
p2 = input("Digite o preço 2º produto: ")
p3 = input("Digite o preço 3 produto: ")
p4 = input("Digite o preço 4º produto: ")
p5 = input("Digite o preço 5º produto: ")

if p1 < p2 and p3 and p4 and p5:
    menor = p1
    print(f'O produto 1 de {p1} reais é o mais barato!!')
if p2 < p1 and p3 and p4 and p5:
    menor = p2
    print(f'O produto 2 de {p2} reais é o mais barato!!')
if p3 < p2 and p1 and p4 and p5:
    menor = p3
    print(f'O produto 2 de {p3} reais é o mais barato!!')
if p4 < p3 and p2 and p1 and p5:
    menor = p4
    print(f'O produto 4 de {p4} reais é o mais barato!!')
if p5 < p4 and p3 and p2 and p1:
    menor = p5
    print(f'O produto 4 de {p4} reais é o mais barato!!')

p1 = input("Digite o 1° preço: ")
p2 = input("Digite o 2° preço: ")
p3 = input("Digite o 3° preço: ")

if p1 < p2 and p3 and p1:
    print('O produto 1 é o mais barato!!')
elif p2 < p1 and p3:
    print('O produto 2 é o mais barato!!')
elif p3 < p1 and p2:
    print('O produto 3 é o mais barato!!')
    
elif p1 == p2 and p1 and p2 < p3:
    print('O produto 1 e 2 são os mais baratos!!')
elif p1 == p3 and p1 and p3 < p2:
    print('O produto 1 e 3 são os mais baratos!!')
elif p2 == p3 and p2 and p3 < p1:
    print('O produto 1 e 2 são os mais baratos!!')

"""Crie um algoritmo em Python que leia três números e mostre-os em ordem decrescente."""

# INSIRA SEU CÓDIGO AQUI

"""As Organizações Mendéz resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes em Python. Faça um programa que receba o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

* salários entre 680,00 e 800,00 : aumento de 15%<br>
* salários entre 800,00 e 2500,00 : aumento de 10%<br>
* salários de 2500,00 em diante : aumento de 5% após o aumento ser realizado.

Informe na tela:
* o salário antes do reajuste;
* o percentual de aumento aplicado;
* o valor do aumento;
* o novo salário, após o aumento.
"""

# INSIRA SEU CÓDIGO AQUI

salario = float(input("Digite  valor do sálario: "))

print('''Selecione o valor do reajuste:
        salários entre 680,00 e 800,00 : aumento de 15%
        salários entre 800,00 e 2500,00 : aumento de 10%
        salários de 2500,00 em diante : aumento de 5% após o aumento ser realizado.
	    \n''')


if salario <= 800:
    percentual = 15

if salario <= 2500:
    percentual = 10
else:
    percentual = 5

percentual = percentual / 100.0
aumento = percentual * salario
novo_salario = salario + aumento




print(f"o salário antes do reajuste: {salario}")
print(f"Percentual de aumento aplicado: {percentual}", '%')
print(f'O valor do aumento é: {aumento}')
print(f"O valor do novo aumento do salário é: {novo_salario}")

